### ISSUE TITLE
[Research] Animation - Find library for animation purposes.

### ISSUE THREAD

**Issue by piotrwasilewski420** [KuzniaCo/chemistry-app#20]
### We need library to do animations in our app that would operate on UI thread and be well documented.

[React Native Reanimated v2](https://docs.swmansion.com/react-native-reanimated/) is a perfect choice for that and matches all of our requirements. It works on UI thread which ensures high performance (60 FPS) and is really well documented and became a standard in a react-native development world.

##### Here is the list of tutorials of what we can do with it

*   [A cheatsheet for everybody who never had any prior experience with this library](https://www.youtube.com/watch?v=dowHt1dckDU)
*   [Best tutorials on this matter](https://www.youtube.com/watch?v=yz9E10Dq8Bg&list=PLjHsmVtnAr9TWoMAh-3QMiP7bPUqPFuFZ)

**Comment by mbacaa** [comment]
I agree with @piotrwasilewski420, React Reanimated v2 sounds good to me.
