### ISSUE TITLE
[Research] Navigation - Find library to navigate through screens.

### ISSUE THREAD

**Issue by mbacaa** [KuzniaCo/chemistry-app#21]
# [Research] Navigation - Find library to navigate through screens.

I suggest using [React Navigation](https://reactnavigation.org/), which provides us views that deliver 60fps animations, and utilize native components. It's well documented and maintained.

[GitHub](//github.com/react-navigation/react-navigation)

There are many tutorials on youtube e.g.

*   [YouTube tutorial 1](https://www.youtube.com/watch?v=UzMbu3XKEoM)
*   [YouTube tutorial 2](https://www.youtube.com/watch?v=FWwKjxSgLl8&list=PLQWFhX-gwJbmtZY4mcRE-k7hL9DigcGS-)
[](https://www.youtube.com/watch?v=FWwKjxSgLl8&list=PLQWFhX-gwJbmtZY4mcRE-k7hL9DigcGS-)

[](https://www.youtube.com/watch?v=FWwKjxSgLl8&list=PLQWFhX-gwJbmtZY4mcRE-k7hL9DigcGS-)

**Comment by piotrwasilewski420** [comment]
I agree it seems to be the best choice.

**Comment by BartoszBrodowski** [comment]
I've tried out basic functionalities of React Navigation and it seemed fine for me.
