### ISSUE TITLE
[Development] Dummy login view

### ISSUE THREAD

**Issue by bartlomiejmont** [KuzniaCo/chemistry-app#7]

**Comment by BartoszBrodowski** [comment]
As I was requested to do, I attach the examplary design for logging screen as well as the link to overall progress of the app's design made by Tamara. The two photos are sketches. One of those is LoFi design (the grey one) and the other one is more HiFi with styling already chosen.

Photos:
![Login_LoFi](https://user-images.githubusercontent.com/94301235/162609650-8151bb4e-2aec-4962-912d-900fe5d8cd7e.png)
![Login_HiFi](https://user-images.githubusercontent.com/94301235/162609653-7c0b6e87-f413-4dcf-9ebe-c82f40acac48.png)

Link to the overall design progress:
https://www.figma.com/file/1vncmdPvqKp8Nu5ttfyY4m/Design---basic?node-id=0%3A1
You can also add comments on figma projects by pressing C and clicking on the canvas. This might be usefull while discussing the ideas and can also help Tamara to improve the design.

**Comment by BartoszBrodowski** [comment]
Final version of the login view looks like this: 
![Final_view](https://user-images.githubusercontent.com/94301235/164556180-e5c75ff0-d63a-402a-b014-2cbc389be78f.png)
